[helpers]

[default]
depends = []

[default.files]
alacritty = "~/.config/alacritty"
bashprofile = "~/.bash_profile"
bashrc = "~/.bashrc"
fish = "~/.config/fish"
gitconf = "~/.gitconfig"
nitrogen = "~/.config/nitrogen"
polybar = "~/.config/polybar"
rofi = "~/.config/rofi"
wallpapers = "~/.wallpapers"
xinit = "~/.xinitrc"
xmonad = "~/.config/xmonad"

[default.variables]
